- hosts: worker-adduser
  become: yes
  roles:
    - {role: adduser, tags: ['adduser']}

- hosts: worker-cassandra
  become: yes
  roles:
    - {role: cassandra-cluster, tags: ['cassandra-cluster']}
    - {role: change-hostname, tags: ['hostname-cass']}

- hosts: worker-postgres-percona
  become: yes
  roles:
    - {role: postgres-percona, tags: ['postgres-percona']}
    - {role: change-hostname, tags: ['hostname-pg']}

    
- hosts: host-reaper
  become: yes
  roles:
    - {role: cassandra-reaper, tags: ['cassandra-reaper']}

- hosts: host-postgres-exporter
  become: yes
  roles:
    - {role: postgres-exporter, tags: ['postgres-exporter']}

- hosts: host-mongodb-service
  become: yes
  roles:
    - {role: mongodb, tags: ['mongodb']}
    - {role: change-hostname, tags: ['hostname-mongodb']}
    - {role: mongodb-exporter, tags: ['mongodb-exporter']}

- hosts: host-elasticsearch-service
  become: yes
  roles:
    - {role: change-hostname, tags: ['hostname-elasticsearch']}

- hosts: mysql
  become: yes
  roles:
    - {role: mysql-cluster, tags: ['mysql']}
