- hosts: worker-cassandra
  become: yes
  roles:
    - {role: cassandra-cluster, tags: ['cassandra-cluster']}
    - {role: adduser, tags: ['adduser']}
    - {role: change-hostname, tags: ['hostname-cass']}

- hosts: worker-postgres-percona
  become: yes
  roles:
    - {role: postgres-percona-v16, tags: ['postgres-percona-v16']}
    - {role: change-hostname, tags: ['hostname-pg']}

    
- hosts: host-reaper
  become: yes
  roles:
    - {role: cassandra-reaper, tags: ['cassandra-reaper']}

- hosts: host-postgres-exporter
  become: yes
  roles:
    - {role: postgres-exporter, tags: ['postgres-exporter']}

- hosts: host-mongodb-service
  become: yes
  roles:
    - {role: mongodb-service, tags: ['mongodb-service']}


