---
- name: Create postgres_exporter directory
  ansible.builtin.file:
    path: "{{ dir_ex }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Download postgres_exporter archive
  ansible.builtin.get_url:
    url: "https://github.com/prometheus-community/postgres_exporter/releases/download/v{{ postgres_exporter_version }}/postgres_exporter-{{ postgres_exporter_version }}.linux-amd64.tar.gz"
    dest: "{{ dir_ex }}/postgres_exporter-{{ postgres_exporter_version }}.linux-amd64.tar.gz"
    owner: root
    group: root
    mode: '0644'

- name: Extract postgres_exporter archive
  ansible.builtin.unarchive:
    src: "{{ dir_ex }}/postgres_exporter-{{ postgres_exporter_version }}.linux-amd64.tar.gz"
    dest: "{{ dir_ex }}"
    remote_src: true
    creates: "{{ dir_ex }}/postgres_exporter-{{ postgres_exporter_version }}.linux-amd64/postgres_exporter"
    owner: root
    group: root

- name: Install postgres_exporter binary
  ansible.builtin.copy:
    src: "{{ dir_ex }}/postgres_exporter-{{ postgres_exporter_version }}.linux-amd64/postgres_exporter"
    dest: /usr/local/bin/postgres_exporter
    remote_src: true
    owner: root
    group: root
    mode: '0755'
  notify: Restart postgres_exporter

- name: Configure postgres_exporter environment
  ansible.builtin.template:
    src: postgres-exporter.env.j2
    dest: "{{ dir_ex }}/postgres_exporter.env"
    owner: postgres
    group: postgres
    mode: '0640'
  notify: Restart postgres_exporter

- name: Config postgres_exporter.yml
  ansible.builtin.template:
    src: postgres_exporter.yml.j2
    dest: "{{ dir_ex }}/postgres_exporter.yml"
    owner: postgres
    group: postgres
    mode: '0640'
  notify: Restart postgres_exporter

- name: Configure postgres_exporter systemd service
  ansible.builtin.template:
    src: postgres_exporter.service.j2
    dest: /etc/systemd/system/postgres_exporter.service
    owner: root
    group: root
    mode: '0644'
  notify: Restart postgres_exporter

- name: Enable and start postgres_exporter
  ansible.builtin.systemd:
    name: postgres_exporter
    enabled: true
    state: started
    daemon_reload: true



