--- 
- name: Creates directory
  ansible.builtin.file:
    path: "{{ dir_ex }}"
    state: directory

- name: file init
  template: src=mongodb_exporter.sh.j2 dest={{ dir_ex }}/mongodb_exporter.sh mode=0777

- name: Creat Directory Mongodb Exporter
  shell: "{{ dir_ex }}/mongodb_exporter.sh > {{ dir_ex }}/log_execute_{{ inventory_hostname }}.txt"

- name: Config mongodb_exporter.service
  template: src=mongodb_exporter.service.j2 dest=/lib/systemd/system/mongodb_exporter.service mode=744

- name: Start mongodb_exporter
  command: systemctl daemon-reload

- name: Enable postgres_exporter
  command: systemctl enable --now mongodb_exporter